### ISSUE TITLE
add an `any` type

### ISSUE THREAD

**Issue by sam-goodwin** [sam-goodwin/punchcard#13]
Do we want to support an `any` type? What would we do in the `Mappers`? Best-effort serialization?

**Comment by pocesar** [comment]
it would be nice. I'm having to set manually every member of a nested JSON body, but I really wanted a punchcard.any() and just stuff the thing inside the dynamodb

**Comment by sam-goodwin** [comment]
I think we should copy (or use) the [DocumentClient](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html) for working with `any` in DynamoDB. It marshals based on the JS type.

The [JSON mapper](https://github.com/sam-goodwin/punchcard/blob/master/packages/punchcard/lib/shape/json/mapper.ts) should just be a no-op - pass the value through to `JSON.stringify`

Future codecs such as Avro (https://github.com/sam-goodwin/punchcard/issues/10) would likely have to throw unless the underlying protocols supported an `any`.

What about [Glue Tables](https://github.com/sam-goodwin/punchcard/blob/master/packages/punchcard/lib/storage/glue/table.ts#L120)? I'm leaning towards throwing an error but we could also use `string` and serialize as JSON.

The most difficult change would be the [DynamoDB Path](https://github.com/sam-goodwin/punchcard/blob/master/packages/punchcard/lib/storage/dynamodb/expression/path.ts#L65) and [JSON Path](https://github.com/sam-goodwin/punchcard/blob/master/packages/punchcard/lib/shape/json/path.ts#L4) DSLs. For example, because the types of a property isn't defined, we can't have a type-safe DynamoDB condition expression like: `if: item => item.anyAttribute.some.path.equals('some string')`. I think the solution is to add an `as` method that lets you explicitly treat a property within a nested object as some type:

```ts
const table = new HashTable(.., {
  shape: {
    anyAttribute: punchcard.any
  }
});

await table.put({
  if: item => item.anyAttribute.some.arbitrary.path.as(string()).equals('some value')
})
```
