### ISSUE TITLE
not a bug or issue, but have to give my kudos

### ISSUE THREAD

**Issue by pocesar** [sam-goodwin/punchcard#23]
this repo showed from the activity from someone I follow, and I've never been this excited with an open source project the way I'm feeling with punchcard. CDK by itself is brilliant, and you managed to take it to the maximum. being both a heavy TS and AWS user, and although still reading the code, I have never seen such a brilliant abstraction in recent years. had my share of serverless, and again, couldn't be more excited for this one to be widespread and receive the proper recognition. 
I'd love to be able to help punchcard in any way, and help make this even greater, but I still need to wrap my head around the whole thing 😄

**Comment by sam-goodwin** [comment]
Hey! Thanks so much for the kind words :) It's been such a pleasure dreaming up this abstraction. I'm glad to hear you're excited about punchcard's potential and taking the time to trawl through the code. Welcome!

I recently released my first blog on punchcard: https://bit.ly/punchcard-cdk and plan on writing a lot more, covering the tech, showing examples, tutorials, videos - all that goodness. Feedback is always welcome. I'll be tweeting ([@samgoodwin89](https://twitter.com/samgoodwin89)) out each new resource so you can follow that if you'd like!

There's also a Gitter that I'll be hanging out in answering questions for anyone looking to learn and contribute. https://gitter.im/punchcard-cdk/community. Come on by and I'll be happy to help you wrap your head around the framework - your new perspective will help me better understand how to document punchcard.

There are plenty of fun problems to solve! Happy to brainstorm ideas and solutions in the issues. Thanks for reaching out, you've reminded me that I need to set up a contributing guide: https://github.com/sam-goodwin/punchcard/issues/24

**Comment by pocesar** [comment]
even though the API might not be 'stable' (per semver), I'm going to give it a shot at PRODUCTION (I'm 100% serious). by using it in a real project, I can give real feedback besides the usual API bike-shedding 💎

**Comment by sam-goodwin** [comment]
That's awesome! I look forward to hearing about your experience.

**Comment by sam-goodwin** [comment]
Thanks again for the kind words and for your time trying out punchcard. Going to close this to keep things clean :)

**Comment by Birowsky** [comment]
I was about to write the same post!

@sam-goodwin, what you’ve done here is mental!

**Comment by sam-goodwin** [comment]
Thanks so much for the support! It really helps my motivation to have you and @pocesar here to bounce ideas off!

Shape refactor (https://github.com/punchcard/punchcard/pull/102) is coming along really nicely - would love your feedback on the PR! :)

**Comment by Birowsky** [comment]
Props are all yours, Sam!

I'm honestly not in a position to give detailed feedback as I'm merely slowly introducing my self with CDK and Punchcard as the better version of it.

I might, however, point out when something is lacking with the introductory documentation. Like, for example, how the current Lambda types don't match the 'getting started' docs ; ]

Keep up the genius work!
